name: Deploy To Heroku

on:
 push:
   branches: [ main ]

jobs:
  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy To Heroku
        uses: see/heroku-deploy@v1.0.0 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_TS}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}

